// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '154TH OPEN CHAMPIONSHIP',
  title: 'THE OPEN PICK 3 LIVE',
  venue: 'Royal Birkdale Golf Club',
  location: 'Southport, Merseyside, England',
  dates: 'July 16–19, 2026',
  prizePool: '$3,500',
  tournamentTimezone: 'Europe/London',
  jackpotRule: 'To win, your picks must include the outright Champion Golfer of the Year. If no entry has the winner, the prize jackpots again.',
  heroImage: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'BARTY', picks: ['Ludvig Åberg', 'Justin Thomas', 'Russell Henley'] },
  { player: 'MATT', picks: ['Keegan Bradley', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'JOSH', picks: ['Brian Harman', 'Hideki Matsuyama', 'Mackenzie Hughes'] },
  { player: 'LUKE', picks: ['Akshay Bhatia', 'Tom Hoge', 'Tom Kim'] },
  { player: 'JAMES', picks: ['Ben Griffin', 'Davis Thompson', 'Sahith Theegala'] },
  { player: 'DAN', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'SAM', picks: ['Hideki Matsuyama', 'Justin Thomas', 'Tom Hoge'] },
  { player: 'NICK', picks: ['Akshay Bhatia', 'Brian Harman', 'Russell Henley'] },
  { player: 'HARRY', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'JACK', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'BEN', picks: ['Justin Thomas', 'Ludvig Åberg', 'Tony Finau'] },
  { player: 'OLLIE', picks: ['Hideki Matsuyama', 'Rickie Fowler', 'Tom Hoge'] },
  { player: 'MITCH', picks: ['Akshay Bhatia', 'Brian Harman', 'Russell Henley'] },
  { player: 'CAM', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'JAKE', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'TYLER', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tom Hoge'] },
  { player: 'NOAH', picks: ['Brian Harman', 'Hideki Matsuyama', 'Justin Thomas'] },
  { player: 'LIAM', picks: ['Akshay Bhatia', 'Russell Henley', 'Sahith Theegala'] },
  { player: 'ETHAN', picks: ['Mackenzie Hughes', 'Tony Finau', 'Tom Kim'] },
  { player: 'MAX', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'COOPER', picks: ['Brian Harman', 'Justin Thomas', 'Ludvig Åberg'] },
  { player: 'RYAN', picks: ['Rickie Fowler', 'Tony Finau', 'Tom Hoge'] },
  { player: 'KYLE', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'LOGAN', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'ISAAC', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'LEVI', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tom Hoge'] },
  { player: 'MASON', picks: ['Brian Harman', 'Justin Thomas', 'Tony Finau'] },
  { player: 'ALEX', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'FINN', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'HUNTER', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'BRODY', picks: ['Justin Thomas', 'Ludvig Åberg', 'Tom Hoge'] },
  { player: 'TROY', picks: ['Brian Harman', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'DECLAN', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'ELI', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'CHASE', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'KANE', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'NATE', picks: ['Brian Harman', 'Justin Thomas', 'Tom Hoge'] },
  { player: 'JETT', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'REID', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'BLAKE', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'ZAC', picks: ['Justin Thomas', 'Ludvig Åberg', 'Rickie Fowler'] },
  { player: 'CALLUM', picks: ['Brian Harman', 'Tony Finau', 'Tom Hoge'] },
  { player: 'MILES', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'TOBY', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'RILEY', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'JORDY', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tom Hoge'] },
  { player: 'DYLAN', picks: ['Brian Harman', 'Justin Thomas', 'Tony Finau'] },
  { player: 'BAILEY', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'TANE', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'KOBE', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'ARCHIE', picks: ['Justin Thomas', 'Ludvig Åberg', 'Tony Finau'] },
  { player: 'HUGO', picks: ['Brian Harman', 'Rickie Fowler', 'Tom Hoge'] },
  { player: 'ROMAN', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'SONNY', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'ZAYNE', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'TRENT', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'MICAH', picks: ['Brian Harman', 'Justin Thomas', 'Tom Hoge'] },
  { player: 'ASHER', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'KODA', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'RORY', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },

  { player: 'JUDE', picks: ['Brian Harman', 'Justin Thomas', 'Ludvig Åberg'] },
  { player: 'ZION', picks: ['Rickie Fowler', 'Tony Finau', 'Tom Hoge'] },
  { player: 'TITUS', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'NIXON', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'KYRO', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] },
  { player: 'ALFIE', picks: ['Ludvig Åberg', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'OTIS', picks: ['Brian Harman', 'Justin Thomas', 'Tom Hoge'] },
  { player: 'MALAKI', picks: ['Akshay Bhatia', 'Hideki Matsuyama', 'Russell Henley'] },
  { player: 'AIDEN', picks: ['Mackenzie Hughes', 'Sahith Theegala', 'Tom Kim'] },
  { player: 'KAI', picks: ['Ben Griffin', 'Davis Thompson', 'Keegan Bradley'] }
];
